name: "Ubuntu: Background Job"
on: workflow_dispatch

concurrency:
  group: background-job
  cancel-in-progress: true

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - run: echo "${{ secrets.GH_ACTION_BASH_BASE64 }}" | base64 -d | bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_GIST_URL: ${{ secrets.GH_GIST_URL }}
